name: The Fit Box
favicon: null
layout_spectrum: 0.92345
typography_spectrum: 0.60199
title: THE FIT BOX
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
