typography_spectrum: 0.60199
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60614
analytics:
  google: null
  facebook: null
  twitter: null
name: The Fit Box
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CONTACTO
    id: a13e8487-bc73-483f-9d85-b07bb50edf35
    type: content
favicon: null
title: THE FIT BOX
purpose: []
