typography_spectrum: 0.5158093187492341
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.27537320530973375
  lightness: 0.8846529019065201
  saturation: 0.19904983579181135
  rhythmicContrast: 0.8560628828126937
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08880027919076383
analytics:
  google: null
  facebook: null
  twitter: null
name: '<<'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CONCEPTO
    id: f14dcc91-c649-42dd-ba06-dbeb3b9fdb59
    type: content
  - name: PRODUCTOS
    id: 52bb2ebd-aa31-4c6c-9cf7-1492efccf698
    type: content
  - name: MARCAS
    id: f1fb8e86-510d-432a-826d-77e0ae9948e2
    type: content
  - name: CONTACTO
    id: a13e8487-bc73-483f-9d85-b07bb50edf35
    type: content
favicon: null
title: THE FIT BOX
description: BIENVENIDO!
purpose: []
