layout_spectrum: 0.24895517132245004
typography_spectrum: 0.6180235692299902
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.26433565956540406
  lightness: 0.9519154322333634
  saturation: 0.9071812983602285
  rhythmicContrast: 0.7314519721549004
name: The Fit Box
favicon: null
title: THE FIT BOX
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
navigation:
  - name: CONTACTO
    id: a13e8487-bc73-483f-9d85-b07bb50edf35
    type: content
