typography_spectrum: 0.6180235692299902
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.26433565956540406
  lightness: 0.9519154322333634
  saturation: 0.9071812983602285
  rhythmicContrast: 0.7314519721549004
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24895517132245004
analytics:
  google: null
  facebook: null
  twitter: null
name: Regresar
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: THE FIT BOX
description: THE FIT BOX
purpose: []
